sudo: false
language: ruby
rvm:
- 2.4.1
cache:
  bundler: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - node_modules
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_237f01759d4b_key -iv $encrypted_237f01759d4b_iv
   -in client-secret.json.enc -out config/client-secret.json -d

before_script:
- docker-compose --version
- docker-compose -f docker-compose.travis.yml build

script:
- docker-compose -f docker-compose.travis.yml run web sh docker/init_app.sh
- docker-compose -f docker-compose.travis.yml up -d
- docker-compose -f docker-compose.travis.yml run -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY web rake spec

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - chmod a+x ./scripts/deploy-staging.sh

deploy:
  - provider: script
    script: ./scripts/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: kubernetes-tests
