sudo: false
language: ruby
rvm:
  - 2.4.1
cache:
  bundler: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - node_modules
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_237f01759d4b_key -iv $encrypted_237f01759d4b_iv
     -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar

before_script:
  - docker-compose --version
  - docker-compose -f docker-compose.travis.yml build

script:
  - docker-compose -f docker-compose.travis.yml run app sh scripts/init_app.sh
  - docker-compose -f docker-compose.travis.yml up -d
  - docker-compose -f docker-compose.travis.yml run app rspec
  - docker-compose -f docker-compose.travis.yml run app rails test:system

# install gcloud sdk
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - chmod a+x ./scripts/deploy-staging.sh

# deploy updated images on kubernetes cluster
deploy:
  - provider: script
    script: ./scripts/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: temporary-stopped # we don't need to use gcloud at the point.
