sudo: required

language: ruby

rvm:
- 2.4.1

services:
  - docker

cache: bundler
#
#before_install:
# - gem update --system

before_script:
  - docker-compose --version
  - docker-compose -f docker-compose.travis.yml build

script:
  - docker-compose -f docker-compose.travis.yml run web sh docker/init_app.sh
  - docker-compose -f docker-compose.travis.yml run -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY web rake spec
