# docker-compose file for travis-ci checks
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.dev.sample

  db:
    image: postgres
    env_file: .env.dev.sample

  redis:
    image: redis
    command: redis-server
    env_file: .env.dev.sample
    ports:
      - '6379:6379'

  web:
    build: .
    env_file: .env.dev.sample
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build: .
    volumes:
      - .:/myapp
    env_file: .env.dev.sample
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
