# docker-compose file for travis-ci checks
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.development.sample
    environment:
    # it helps us run elasticsearch on systems with no significant resources
      ES_JAVA_OPTS: -Xms1g -Xmx1g # by default - 10g
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: postgres
    env_file: .env.development.sample
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    env_file: .env.development.sample
    ports:
      - '6379:6379'

  web:
    build: .
    env_file: .env.development.sample
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build: .
    volumes:
      - .:/usr/src/app
    env_file: .env.development.sample
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
