# docker-compose file for production environment
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.production
    environment:
    # it helps us run elasticsearch on systems with no significant resources
      ES_JAVA_OPTS: -Xms1g -Xmx1g # by default - 10g
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: postgres
    env_file: .env.production
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    env_file: .env.production
    ports:
      - '6379:6379'

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./log:/usr/src/app/log
    links:
      - web
    ports:
      - "80:80"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.prod
    env_file: .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file: .env.production
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml -e production
