# docker-compose file for production environment
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.production.sample
    environment:
    # it helps us run elasticsearch on systems with no significant resources
      ES_JAVA_OPTS: -Xms1g -Xmx1g # by default - 10g
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: postgres
    env_file: .env.production.sample
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    env_file: .env.production.sample
    ports:
      - '6379:6379'

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RAILS_ENV: production
    env_file: .env.production.sample
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env.production.sample
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml -e production
