# docker-compose file for development environment
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env

  db:
    image: postgres
    env_file: .env

  redis:
    image: redis
    command: redis-server
    env_file: .env
    ports:
      - '6379:6379'

  web:
    build: .
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build: .
    volumes:
      - .:/myapp
    env_file: .env
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
