# docker-compose file for development environment
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.development
    environment:
    # it helps us run elasticsearch on systems with no significant resources
      ES_JAVA_OPTS: -Xms1g -Xmx1g # by default - 10g

  db:
    image: postgres
    env_file: .env.development

  redis:
    image: redis
    command: redis-server
    env_file: .env.development
    ports:
      - '6379:6379'

  web:
    build: .
    env_file: .env.development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch

  sidekiq:
    build: .
    volumes:
      - .:/usr/src/app
    env_file: .env.development
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
