# docker-compose file for development environment
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    env_file: .env.development
    environment:
    # it helps us run elasticsearch on systems with no significant resources
      ES_JAVA_OPTS: -Xms1g -Xmx1g # by default - 10g
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: postgres
    env_file: .env.development
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    env_file: .env.development
    ports:
      - '6379:6379'

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - web
    ports:
      - "80:80"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file: .env.development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch
      - webpacker
    stdin_open: true
    tty: true

  sidekiq:
    build:
      context: .
      dockerfile: docker/sidekiq/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file: .env.development
    depends_on:
      - db
      - redis

  webpacker:
    build:
      context: .
      dockerfile: docker/webpacker/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"