# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: 0.0.0.0
  port: 3000

development:
  <<: *default

test:
  <<: *default
  enabled: false
  host: web

production:
  <<: *default
  enabled: false
