default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: teachbot_development

test:
  <<: *default
  database: teachbot_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
